#!/usr/bin/env bash

#: exec_target = cli

## Build assets for production environment
##
## Usage: fin prod

# Abort if anything fails
set -e

#-------------------------- Settings --------------------------------
#-------------------------- END: Settings --------------------------------

#-------------------------- Helper functions --------------------------------
  source ${PROJECT_ROOT}/.composer/bin/helpers
#-------------------------- END: Helper functions --------------------------------

#-------------------------- Execution --------------------------------
  echo-green "
╔═╗┬─┐┌─┐┌┬┐┬ ┬┌─┐┌┬┐┬┌─┐┌┐┌  ╔╦╗┌─┐┌┬┐┌─┐   
╠═╝├┬┘│ │ │││ ││   │ ││ ││││  ║║║│ │ ││├┤   
╩  ┴└─└─┘─┴┘└─┘└─┘ ┴ ┴└─┘┘└┘  ╩ ╩└─┘─┴┘└─┘"
  echo-yellow "Build Production"
  echo-green "  [$] ${light_green}fin prod"
  cd ${PROJECT_ROOT}
  yarn build
  echo-green "  [x] ${light_green}Built!"
#-------------------------- END: Execution --------------------------------
